default_install_hook_types :
 [pre-commit]
  
repos:
 - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
   rev: v2.12.0
   hooks:
     - id: pretty-format-java
       args: [--autofix , --google-java-formatter-version=1.21.0]
  
 - repo: local
   hooks:
     - id: check_commiter_email_id
       name: Check committer email id
       entry: python3 check_email_domain.py
       language: python
       stages: [pre-commit]

 - repo: local
   hooks:
     - id: check_commiter_user_name
       name: Check committer user name
       entry: python3 check_username_domain.py
       language: python
       stages: [pre-commit]

 - repo: local
   hooks:
     - id: check_commiter_email_id_sh
       name: Check committer email id
       entry:  bash check_email_domain.sh
       language: system
       stages: [pre-commit]

 - repo: local
   hooks:
     - id: check_commiter_user_name_sh
       name: Check committer user name
       entry: bash check_username_domain.sh
       language: system
       stages: [pre-commit]

